# Generated by Django 5.2.6 on 2025-09-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha_creacion']},
        ),
    ]
