# Generated by Django 5.2.6 on 2025-09-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0002_alter_nota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
